# Default values for alertmanager-matrix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: silkeh/alertmanager_matrix
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # latest with current:
  #  - amd64      @sha256:2afd6d70f39fdfa98f11758090506f7845aee33cc8d900f9fe39a2574c272063
  #  - 386 /x86   @sha256:beca95e9595de7169ab34406936b585d6676ce03a7fe51815b3a6a4944f9dd6d
  #  - arm v6     @sha256:ce40ea204497bfc9b2e796cf984eba53ba7c59164d39dcd4c11f0ca561e57eca
  #  - arm v7     @sha256:59ce3dfc73be5f70b873fe095e1eee4e0fe1f256b39f8f051ad0a2ffe9d1177e
  #  - arm v8     @sha256:fdbf50e944f8118dd1a44dde21b9cc098fb13837031e2f2492c148848c3d3cc8
  #  - ppc64le    @sha256:4ce02adbf4efe3ad04422e35bd4e87442a7c899fea13988adaeb985c720e0c63
  #  - s390x      @sha256:a202252cc00664a17caa5760f749b35a7b71253d1b1474b861f233e83ada1c76
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

bot:
  matrix:
    homeserver: "http://localhost:8008"
    userID: "bot"
    token: "SECRET_TOKEN"
    rooms:
     - "!not_existing:matrix.org"
  alertmanager: "http://localhost:9093"
  showLabels: false
  messageType: "m.notice"
  icons:
    alert:       "ðŸ””ï¸"
    information: "â„¹ï¸"
    info:        "â„¹ï¸"
    warning:     "âš ï¸"
    critical:    "ðŸš¨"
    error:       "ðŸš¨"
    resolved:    "âœ…"
    silenced:    "ðŸ”•"
  colors:
    alert:       "black"
    information: "blue"
    info:        "blue"
    warning:     "orange"
    critical:    "red"
    error:       "red"
    resolved:    "green"
    silenced:    "gray"
  # get from: https://gitlab.com/silkeh/alertmanager_matrix/-/blob/master/pkg/bot/formatting.go
  template:
    text: >
      {{ range .Alerts }}
        {{.StatusString|icon}}
        {{.StatusString|upper}}
        {{.AlertName}}:
        {{.Summary}}
        {{if ne .Fingerprint \"\"}}
          ({{.Fingerprint}})
        {{end}}
        {{if $.ShowLabels}}
          , labels:
          {{.LabelString}}
        {{end}}
        \n
      {{ end -}}
    html: >
      {{ range .Alerts }}
        <font color="{{.StatusString|color}}">
          {{.StatusString|icon}}
          <b>{{.StatusString|upper}}</b>
          {{.AlertName}}:
        </font>
        {{.Summary}}
        {{if ne .Fingerprint ""}}
          ({{.Fingerprint}})
        {{end}}
        {{if $.ShowLabels}}
          <br/>
          <b>Labels:</b>
          <code>{{.LabelString}}</code>
         {{end}}
         <br/>
      {{- end -}}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4051

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
